### ISSUE TITLE
Highlight rounded

### ISSUE THREAD

**Issue by cristinaITdeveloper** [yaminncco/vue-guided-tour#1]
Great library. Thanks for the work. 
How can I do to have the highlighted area with the rounded edge?
Thank you!

**Comment by yaminncco** [comment]
Right now styling the highlight is not possible.

**Comment by martinszeltins** [comment]
I would also love to be able to do rounded highlights

**Comment by yaminncco** [comment]
It took some time but you can now customize with CSS variables

```
:root {
  --vgt-overlay-background: rgba(255, 255, 255, 0.80);
  --vgt-overlay-border-radius: 10px;
  --vgt-overlay-border-width: 2px;
  --vgt-overlay-border-color: #000;
}
```
