### ISSUE TITLE
vue-guided-tour with Nuxt

### ISSUE THREAD

**Issue by kishanppatel** [yaminncco/vue-guided-tour#2]
How can I integrate this package `vue-guided-tour` with `Nuxt.js`

<img width="1028" alt="Screenshot 2022-07-29 at 4 22 31 PM" src="https://user-images.githubusercontent.com/50623010/181744435-0ce0cb90-faaa-4d60-b23b-9745cf6a358e.png">
What is the problem, I didn't understand. 

Nuxt Project > Plugins > vue-guided-tour.js

![Screenshot 2022-07-29 at 4 26 46 PM](https://user-images.githubusercontent.com/50623010/181745424-82d1fd0a-b6c0-4eee-bb18-77712963b000.png)

**Comment by yaminncco** [comment]
Works with Nuxt3 follow doc https://v3.nuxtjs.org/guide/directory-structure/plugins/#vue-plugins

**Comment by kishanppatel** [comment]
My Nuxt version is v2.14.5

**Comment by kishanppatel** [comment]
I'm unable to use this package in the current nuxt version (v2.14.5), I got this error:
<img width="1432" alt="Screenshot 2022-08-01 at 12 57 38 AM" src="https://user-images.githubusercontent.com/50623010/182042087-73405e4e-5bcc-4110-8522-ebf39e9d0283.png">

I think this error comes from this line of code, `globalProperties` is got undefined(It's because of vue version):
<img width="626" alt="Screenshot 2022-08-01 at 12 59 35 AM" src="https://user-images.githubusercontent.com/50623010/182042149-4cbb902f-f019-4c10-8569-3e4f58d4ecf0.png">

**Comment by yaminncco** [comment]
Works only with Nuxt3, this component doesn't support Vue2
