### ISSUE TITLE
Cannot use the lib

### ISSUE THREAD

**Issue by colin-guyon** [yaminncco/vue-guided-tour#3]
Hello, and sorry for this question:
Has someone already tried to use it with Vue 2 ?
I'm not sure that this is the cause, but when I try to import vue-guided-tour I get this error:
```
 error  in ./node_modules/vue-guided-tour/dist/vue-guided-tour.esm.js

Module parse failed: Unexpected token (1287:30)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|           ...stepObj.popover,
|           role: "dialog",
>           id: stepObj.popover?.id || `popover-${uid}`,
|           "aria-labelledby": stepObj.title
|             ? `${stepObj.popover?.id || uid}-title`
```

The Vue app was created using the standard vue-cli, but I can't migrate to Vue 3 for now.
I tried using `require` but this is not better.

Do you have an idea of the cause ? I never had such error for other Vue libraries.

for the usage I followed https://yaminncco.github.io/vue-guided-tour/getting-started.html#usage
Thanks you very much

**Comment by yaminncco** [comment]
Vue2 is not supported
